version: "3.8"
services:
  validator1:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: validator1
    command: ["/app/cpp-consensus/build/poa_node", "1", "5001", "validator2", "5002"]
    networks:
      - mvpnet
    ports:
      - "5001:5001"

  validator2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: validator2
    command: ["/app/cpp-consensus/build/poa_node", "2", "5002", "validator1", "5001"]
    networks:
      - mvpnet
    ports:
      - "5002:5002"

networks:
  mvpnet:
    driver: bridge
